# Generated by Django 5.1.4 on 2025-01-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gamegeneration_delete_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegeneration',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='gamegeneration',
            name='names',
        ),
        migrations.AddField(
            model_name='gamegeneration',
            name='ability',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamegeneration',
            name='main_region',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gamegeneration',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
